version: '3.7'
services:
  store-api:
    build: .
    image: 'store-api:latest'
    container_name: store-api
    ports:
      - 80:80
    networks:
      - store
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: unless-stopped
networks:
  store:
    external:
      name: store
